platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

project '../modern-design/ModernDesign.xcodeproj'
workspace '../modern-design/ModernDesign.xcworkspace'

target 'ModernDesignTests' do
# pod 'SwiftCommons', git: 'https://github.com/roxiemobile/swift-commons.ios.git', tag: '1.0.0'
  pod 'SwiftCommons', git: 'https://github.com/kolyasev/swift-commons.ios.git', tag: '1.0.0'

  pod 'ModernDesign', path: '../../'
end
