platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

project '../modern-design/ModernDesign.xcodeproj'
workspace '../modern-design/ModernDesign.xcworkspace'

target 'ModernDesignTests' do

  pod 'SwiftCommons/Core/Data', :git => 'https://github.com/roxiemobile/swift-commons.ios.git', :branch => 'sandbox'

  pod 'ModernDesign', path: '../../'
end
