source 'https://github.com/roxiemobile/static-cocoa-frameworks.ios.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

workspace '../RoxieMobile.ModernDesign/ModernDesign.xcworkspace'


# MARK: - Methods

def pod_from(name, *args)
  name = name.split('/').tap { |arr| arr[0] = "#{arr[0]}-SCF53" }.reject(&:empty?).join('/')
  pod(name, *args)
end

def inject_shared_dependencies_1
  pod_from 'SwiftCommons/Lang', '~> 1.5.0'
end

def inject_shared_dependencies_2
  pod 'SwiftLint', '~> 0.40.3'
end


# MARK: - Sources

target 'ModernDesign.Extensions' do
  project '../RoxieMobile.ModernDesign/Sources/Extensions/ModernDesign.Extensions.xcodeproj'

  # Dependencies
  inject_shared_dependencies_1
  inject_shared_dependencies_2
end
